default_language_version:
  python: python3.8
repos:
- repo: https://github.com/ambv/black
  rev: 19.10b0
  hooks:
    - id: black
      name: black
      language: system
      entry: black
      types: [python]
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.21
  hooks:
    - id: isort
      name: isort
      language: system
      entry: isort -rc .
      types: [python]
- repo: https://github.com/PyCQA/flake8
  rev: 3.8.3
  hooks:
    - id: flake8
      name: flake8
      language: system
      entry: flake8
      types: [python]
- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v2.5.3
  hooks:
    - id: pylint
      name: pylint
      language: system
      entry: pylint
      types: [python]
      files: ^flask_jsonrpc/
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.780
  hooks:
    - id: mypy
      name: mypy
      language: system
      entry: mypy
      types: [python]
      files: ^flask_jsonrpc/


